language: go

go:
  - 1.7.x

install:
  - go get -t
  - GOOS=darwin GOARCH=amd64 go get
  - GOOS=linux GOARCH=amd64 go get
  - GOOS=windows GOARCH=amd64 go get

script:
  - go test ./
  - GOOS=darwin GOARCH=amd64 go build -o sdk-doctor-macos
  - GOOS=linux GOARCH=amd64 go build -o sdk-doctor-linux
  - GOOS=windows GOARCH=amd64 go build -o sdk-doctor-windows.exe
